vtheader = {
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0",
    "Accept": "application/json",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate, br",
    "Referer": "https://www.virustotal.com/",
    "Content-Type": "application/json",
    "X-Tool": "vt-ui-main",
    "X-App-Version": "v1x236x2",
    "Accept-Ianguage": "en-US,en;q=0.9,es;q=0.8",
    "X-Vt-Anti-Abuse-Header": "MTczODczOTA4NjQtWkc5dWRDQmlaU0JsZG1scy0xNzAyOTk1NTkxLjAxNg==",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "Te": "trailers",
}